name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ðŸš€
on:
  push:
    branches:
      - ci_cd_implementation
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    env:
      SSH_PRIVATE_KEY_LOCALCOMPUTER: ${{ secrets.SSH_PRIVATE_KEY_LOCALCOMPUTER }}
      MY_VPS_USER: ${{ secrets.MY_VPS_USER }}
      MY_VPS_IP_ADDRESS: ${{ secrets.MY_VPS_IP_ADDRESS }}
      MY_VPS_PROJECT_PATH: ${{ secrets.MY_VPS_PROJECT_PATH }}
      DAY_OF_WEEK: Monday
    steps:
      - run: echo "ðŸŽ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ðŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ðŸ”Ž The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - run: ls -la
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: ls -la
      - run: echo "ðŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ðŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ðŸ This job's status is ${{ job.status }}."
      - run: echo "$SSH_PRIVATE_KEY_LOCALCOMPUTER" 
      - run: echo "$DAY_OF_WEEK"
      - run: echo "test" >> abc.txt
      - run: cat abc.txt
      # - run: ssh-agent -s
      # - run: eval $(ssh-agent -s)
      # - run: ssh-add <(echo "$SSH_PRIVATE_KEY_LOCALCOMPUTER")
      # - name: Set up SSH agent
        # uses: webfactory/ssh-agent@v0.5.4
        # with:
          # ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_LOCALCOMPUTER }}
      # - run: |
      #     eval $(ssh-agent -s)
      #     ssh-add <(echo "$SSH_PRIVATE_KEY_LOCALCOMPUTER")
      #     mkdir -p ~/.ssh
      #     ssh-keyscan -H $MY_VPS_IP_ADDRESS >> ~/.ssh/known_hosts
      #     ssh $MY_VPS_USER@$MY_VPS_IP_ADDRESS << 'EOF'
      #       whoami
      #       ls
      #       cd projects
      #       ls
      #       cd ESS-microservices
      #       ls
      #       # cd $MY_VPS_PROJECT_PATH
      #       cat ~/.bashrc
      #       . ~/.bashrc
      #       ll
      #     EOF
      - run: echo "ðŸ This job's status is ${{ job.status }}."
