name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on:
  push:
    branches:
      - ci_cd_implementation
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    env:
      SSH_PRIVATE_KEY_LOCALCOMPUTER: ${{ secrets.SSH_PRIVATE_KEY_LOCALCOMPUTER }}
      MY_VPS_USER: ${{ secrets.MY_VPS_USER }}
      MY_VPS_IP_ADDRESS: ${{ secrets.MY_VPS_IP_ADDRESS }}
      MY_VPS_PROJECT_PATH: ${{ secrets.MY_VPS_PROJECT_PATH }}
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."
      - run: eval $(ssh-agent -s)
      - run: ssh-add <(echo "$SSH_PRIVATE_KEY_LOCALCOMPUTER")
      - run: ssh-keyscan -H $MY_VPS_IP_ADDRESS >> ~/.ssh/known_hosts
      - run: ssh $MY_VPS_USER@$MY_VPS_IP_ADDRESS
      - run: cd $MY_VPS_PROJECT_PATH
      - run: touch abc.xyz
      - run: echo "ğŸ This job's status is ${{ job.status }}."
